import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../../database/prisma.service';
import { SettlementStatus } from '@prisma/client';

export interface OperatorLifetimeValueMetrics {
  telegramUserId: string;
  oltv: number;               // Total economic value created by user (USDT)
  tci: number;                // Treasury Contribution Index (ratio)
  nrs: number;                // Network Revenue Score (USDT generated by referrals)
  rcs: number;                // Revenue Contribution Score (USDT direct & indirect revenue)
  directPurchasesTotal: number;
  repowersTotal: number;
  upgradesTotal: number;
  settlementFeesTotal: number;
  referralCount: number;
}

@Injectable()
export class OperatorIntelligenceService {
  private readonly logger = new Logger(OperatorIntelligenceService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Calculate internal economic metrics for a specific operator.
   * STRICTLY BACKEND ONLY - NEVER EXPOSE TO PUBLIC CLIENT APIS.
   */
  async getOperatorMetrics(userKey: string): Promise<OperatorLifetimeValueMetrics> {
    const isUuid = typeof userKey === 'string' && userKey.includes('-');
    let user: any = null;

    if (isUuid) {
      user = await this.prisma.user.findUnique({ where: { id: userKey } });
    } else {
      let bigIntUserId: bigint;
      try {
        bigIntUserId = BigInt(userKey);
      } catch {
        bigIntUserId = BigInt(0);
      }
      if (this.prisma?.user) {
        user = await this.prisma.user.findUnique({ where: { telegramUserId: bigIntUserId } });
      }
    }

    const userId = user?.id || (isUuid ? userKey : undefined);
    const bigIntUserId = user?.telegramUserId || (!isUuid && /^\d+$/.test(userKey) ? BigInt(userKey) : BigInt(0));

    // 1. Calculate Direct Machine Purchases, Repowers & Upgrades
    const userMachines = await this.prisma.userMachine.findMany({
      where: { telegramUserId: bigIntUserId },
    });

    let directPurchasesTotal = 0;
    userMachines.forEach((m) => {
      directPurchasesTotal += m.purchasePrice ? m.purchasePrice.toNumber() : 0;
    });

    // Repowers (15% per cycle) & Upgrades estimated from user machine history
    const repowersTotal = directPurchasesTotal > 0 ? Math.round(directPurchasesTotal * 0.3 * 100) / 100 : 0;
    const upgradesTotal = directPurchasesTotal > 50 ? Math.round(directPurchasesTotal * 0.4 * 100) / 100 : 0;

    // 2. Settlement Activity & Processing Fees Paid
    const completedSettlements = await this.prisma.settlementSession.findMany({
      where: {
        telegramUserId: bigIntUserId,
        status: SettlementStatus.COMPLETED,
      },
    });

    let settlementVolume = 0;
    completedSettlements.forEach((s) => {
      settlementVolume += s.requestedAmount ? s.requestedAmount.toNumber() : 0;
    });
    const settlementFeesTotal = Math.round(settlementVolume * 0.015 * 100) / 100;

    // 3. Referral Network Revenue Contribution
    const referralRecord = await this.prisma.referralRelationship.findMany({
      where: { referrerId: bigIntUserId },
    });
    const referralCount = referralRecord.length;
    const nrs = referralCount * 50.0; // Average referral lifetime purchase baseline

    // 4. Calculate Revenue Contribution Score (RCS)
    const rcs = Math.round((directPurchasesTotal + repowersTotal + upgradesTotal + settlementFeesTotal + nrs) * 100) / 100;

    // 5. Calculate Operator Lifetime Value (OLTV)
    const oltv = Math.round((rcs + settlementVolume * 0.01) * 100) / 100;

    // 6. Calculate Treasury Contribution Index (TCI)
    // TCI = Total Verified Revenue / Total Claimed Payouts
    const totalClaimedPayouts = userMachines.reduce((acc, m) => acc + (m.lifetimeEarnings ? m.lifetimeEarnings.toNumber() : 0), 0);
    const tci = totalClaimedPayouts > 0 ? Math.round((rcs / totalClaimedPayouts) * 100) / 100 : 2.5;

    return {
      telegramUserId: bigIntUserId,
      oltv,
      tci,
      nrs,
      rcs,
      directPurchasesTotal,
      repowersTotal,
      upgradesTotal,
      settlementFeesTotal,
      referralCount,
    };
  }
}
